- name: Gather main ethernet interface
  ansible.builtin.set_fact:
    main_interface: "{{ ansible_default_ipv4.interface }}"

- name: Display the main ethernet interface
  ansible.builtin.debug:
    msg: "The main ethernet interface is {{ main_interface }}"

- name: Render keepalived config
  template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /tmp/keepalived.conf
    mode: '0644'
  changed_when: false

- name: Register sha for old file
  stat:
    path: "/etc/keepalived/keepalived.conf"
    checksum: sha1
    get_checksum: yes
  register: file_1_checksum

- name: Register sha for new file
  stat:
    path: "/tmp/keepalived.conf"
    checksum: sha1
    get_checksum: yes
  register: file_2_checksum

- name: Copy file using command module
  ansible.builtin.command:
    cmd: cp /tmp/keepalived.conf /etc/keepalived/keepalived.conf
  register: copy_result
  when: file_1_checksum.stat.checksum != file_2_checksum.stat.checksum  

- name: Restart service keepalived
  ansible.builtin.systemd_service:
    name: keepalived
    enabled: true

- name: Restart service keepalived
  ansible.builtin.systemd_service:
    name: keepalived  
    state: restarted
    daemon_reload: true
  when: file_1_checksum.stat.checksum != file_2_checksum.stat.checksum
  ignore_errors: true
